all_quran = {
    'الفاتحة'    : True
    ,'البقرة'    : True
    ,'آل عمران'  : True
,'النساء'    : False
,'المائدة'   : False
,'الأنعام'    : False
,'الأعراف'    : False
,'الأنفال'    : False
,'التوبة'    : False
    ,'يونس'      : True
    ,'هود'       : True
    ,'يوسف'      : True
    ,'الرعد'     : True
    ,'ابراهيم'   : True
    ,'الحجر'     : True
    ,'النحل'     : True
,'الإسراء'    : False
,'الكهف'     : False
,'مريم'      : False
,'طه'        : False
,'الأنبياء'   : False
,'الحج'      : False
,'المؤمنون'  : False
,'النور'     : False
,'الفرقان'   : False
,'الشعراء'   : False
,'النمل'     : False
,'القصص'     : False
,'العنكبوت'  : False
,'الروم'     : False
,'لقمان'     : False
,'السجدة'    : False
,'الأحزاب'    : False
,'سبإ'       : False
,'فاطر'      : False
,'يس'        : False
    ,'الصافات'   : True
    ,'ص'         : True
    ,'الزمر'     : True
    ,'غافر'      : True
    ,'فصلت'      : True
    ,'الشورى'    : True
    ,'الزخرف'    : True
    ,'الدخان'    : True
    ,'الجاثية'   : True
    ,'الأحقاف'    : True
    ,'محمد'      : True
    ,'الفتح'     : True
    ,'الحجرات'   : True
    ,'ق'         : True
    ,'الذاريات'  : True
    ,'الطور'     : True
    ,'النجم'     : True
    ,'القمر'     : True
    ,'الرحمن'    : True
    ,'الواقعة'   : True
    ,'الحديد'    : True
    ,'المجادلة'  : True
    ,'الحشر'     : True
    ,'الممتحنة'  : True
    ,'الصف'      : True
    ,'الجمعة'    : True
    ,'المنافقون' : True
    ,'التغابن'   : True
    ,'الطلاق'     : True
    ,'التحريم'   : True
    ,'الملك'     : True
    ,'القلم'     : True
    ,'الحاقة'    : True
    ,'المعارج'   : True
    ,'نوح'       : True
    ,'الجن'      : True
    ,'المزمل'    : True
    ,'المدثر'    : True
    ,'القيامة'   : True
    ,'الانسان'    : True
    ,'المرسلات'   : True
    ,'النبإ'     : True
    ,'النازعات'  : True
    ,'عبس'       : True
    ,'التكوير'   : True
    ,'الإنفطار'   : True
    ,'المطففين'  : True
    ,'الإنشقاق'   : True
    ,'البروج'    : True
    ,'الطارق'    : True
    ,'الأعلى'     : True
    ,'الغاشية'   : True
    ,'الفجر'     : True
    ,'البلد'     : True
    ,'الشمس'     : True
    ,'الليل'     : True
    ,'الضحى'     : True
    ,'الشرح'     : True
    ,'التين'     : True
    ,'العلق'     : True
    ,'القدر'     : True
    ,'البينة'    : True
    ,'الزلزلة'   : True
    ,'العاديات'  : True
    ,'القارعة'   : True
    ,'التكاثر'   : True
    ,'العصر'     : True
    ,'الهمزة'    : True
    ,'الفيل'     : True
    ,'قريش'      : True
    ,'الماعون'   : True
    ,'الكوثر'    : True
    ,'الكافرون'  : True
    ,'النصر'     : True
    ,'المسد'     : True
    ,'الإخلاص'     : True
    ,'الفلق'     : True
    ,'الناس'     : True
}


get_memorized_or_not_memorized = \
    lambda is_memorized: [ k for k, v in all_quran.items() if v is is_memorized ]

memorized     = get_memorized_or_not_memorized(is_memorized=True)
not_memorized = get_memorized_or_not_memorized(is_memorized=False)



assert len(memorized) + len(not_memorized) == 114 \
            , 'memorized + not_memorized != 114'
